// Package main Question Parser API
//
//	@title			Question Parser & Google Sheets Exporter API
//	@version		1.0
//	@description	Stateless API that parses raw MCQ question text and exports to Google Sheets.
//	@contact.name	SmartSystem Support
//	@BasePath		/
//	@schemes		http
package main

import (
	"log"
	"net/http"

	"github.com/rs/cors"
	httpSwagger "github.com/swaggo/http-swagger"

	_ "question_input_smartsystem/docs" // generated by swag init
	"question_input_smartsystem/internal/handler"
)

func main() {
	mux := http.NewServeMux()

	// API Routes
	mux.HandleFunc("/convert", handler.ConvertHandler)
	mux.HandleFunc("/parse", handler.ParseHandler)
	mux.HandleFunc("/export", handler.ExportHandler)

	// Health check
	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Write([]byte(`{"status":"ok"}`))
	})

	// Swagger UI at /swagger/
	mux.HandleFunc("/swagger/", httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"),
	))

	// CORS middleware
	c := cors.New(cors.Options{
		AllowedOrigins:   []string{"*"},
		AllowedMethods:   []string{"GET", "POST", "OPTIONS", "PUT", "DELETE"},
		AllowedHeaders:   []string{"*"},
		AllowCredentials: false,
	})

	h := c.Handler(mux)

	port := ":6060"
	log.Printf("🚀 Question Parser API running on http://localhost%s", port)
	log.Printf("   POST /convert  — Convert text to JSON")
	log.Printf("   POST /parse    — Parse and validateJSON")
	log.Printf("   POST /export   — Export to Google Sheets")
	log.Printf("   GET  /health   — Health check")
	log.Printf("   GET  /swagger/ — Swagger UI")

	if err := http.ListenAndServe(port, h); err != nil {
		log.Fatalf("Server failed to start: %v", err)
	}
}
